language: cpp
install:
  - pip install --user cmake
jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
  - sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - cmake --build . -- -j2
