image:
  - Visual Studio 2019
clone_folder: c:\project\source
clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
build_script:
  - cmd: >-
      mkdir build

      cd build

      cmake c:\project\source -G "Visual Studio 16 2019" -A win32 -DCMAKE_BUILD_TYPE:STRING=Release

      cmake --build . --config "Release"